@echo off
echo 正在启动AI Agent完整服务...
echo =====================================
echo 启动后端服务 (Flask)...
start "AI Agent Backend" cmd /k "cd /d %~dp0backend && python app.py"
echo 后端服务将在 http://127.0.0.1:5000 运行
echo.
echo 启动前端服务 (Vue)...
start "AI Agent Frontend" cmd /k "cd /d %~dp0frontend && npm run dev"
echo 前端服务将在 http://localhost:5173 运行
echo =====================================
echo 所有服务正在启动中...
echo 请在浏览器中访问 http://localhost:5173 开始使用AI助手
echo 按任意键关闭此窗口...
pause >nul